# this is the configuration file of typos (spell checker)
# https://github.com/crate-ci/typos

[files]
# excluded file
extend-exclude = [
	"yts/testdata", # third-party test data
]

# setting for Go files configuration
[type.go]
extend-ignore-re = [
	'ba-dum-tss\W+', # this one can be found in test files
	'"yYnNtTfFoO',   # this one can be found in test files
	'ba\?r',         # this one can be found in test files
]

[type.go.extend-words]
# Here is a list of words we want to ignore in Go files
typ = "typ"  # commonly used abbreviation for "type" in Go as "type" is a reserved identifier

